name: db-init-ecr

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'db-init/**'
      - '.github/workflows/db-init-ecr.yml'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPO_URL_DB: ${{ secrets.ECR_REPO_URL_DB }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPO_URL_DB }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./db-init
          file: ./db-init/dockerfile
          push: true
          tags: |
            ${{ env.ECR_REPO_URL_DB }}:${{ github.sha }}
            ${{ env.ECR_REPO_URL_DB }}:latest
