name: despachos-deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPO_URL_BACKEND: ${{ secrets.ECR_REPO_URL_BACKEND }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPO_URL_BACKEND }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Render ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ secrets.DESPACHOS_ECS_TASK_DEFINITION }}
          container-name: ${{ secrets.DESPACHOS_ECS_CONTAINER_NAME }}
          image: ${{ env.ECR_REPO_URL_BACKEND }}:${{ github.sha }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ secrets.DESPACHOS_ECS_SERVICE }}
          cluster: ${{ secrets.DESPACHOS_ECS_CLUSTER }}
          wait-for-service-stability: true